$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    dots:false,
    autoplay:true,
    autowidth:true,
    startPosition:1,
    responsive:{
        0:{
            items:1
        },
        400:{
            items:1
        },
        600:{
            items:1
        },
        800:{
            items:1
        },
        1000:{
            items:1
        },
       
    }
})